//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wApiMobileForCache.wsIngresosDiarios {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="wsIngresosDiarios.IngresosDiariosSoap")]
    public interface IngresosDiariosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetFichada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetFichada(string pIde, long pFecha, string pHora, long pTipMov, string pRelojId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetFichada", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SetFichadaAsync(string pIde, long pFecha, string pHora, long pTipMov, string pRelojId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetFichadaByDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetFichadaByDocumento(long pDni, long pFecha, string pHora, long pTipMov, string pRelojId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetFichadaByDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SetFichadaByDocumentoAsync(long pDni, long pFecha, string pHora, long pTipMov, string pRelojId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetIngresoAndroid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetIngresoAndroid(string pLeg, long pDni, string pMov, long pTipMov, decimal pLat, decimal pLon, string pNroTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.IngresosDiarios.SetIngresoAndroid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SetIngresoAndroidAsync(string pLeg, long pDni, string pMov, long pTipMov, decimal pLat, decimal pLon, string pNroTel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngresosDiariosSoapChannel : wApiMobileForCache.wsIngresosDiarios.IngresosDiariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngresosDiariosSoapClient : System.ServiceModel.ClientBase<wApiMobileForCache.wsIngresosDiarios.IngresosDiariosSoap>, wApiMobileForCache.wsIngresosDiarios.IngresosDiariosSoap {
        
        public IngresosDiariosSoapClient() {
        }
        
        public IngresosDiariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngresosDiariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresosDiariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresosDiariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SetFichada(string pIde, long pFecha, string pHora, long pTipMov, string pRelojId) {
            return base.Channel.SetFichada(pIde, pFecha, pHora, pTipMov, pRelojId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SetFichadaAsync(string pIde, long pFecha, string pHora, long pTipMov, string pRelojId) {
            return base.Channel.SetFichadaAsync(pIde, pFecha, pHora, pTipMov, pRelojId);
        }
        
        public System.Data.DataSet SetFichadaByDocumento(long pDni, long pFecha, string pHora, long pTipMov, string pRelojId) {
            return base.Channel.SetFichadaByDocumento(pDni, pFecha, pHora, pTipMov, pRelojId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SetFichadaByDocumentoAsync(long pDni, long pFecha, string pHora, long pTipMov, string pRelojId) {
            return base.Channel.SetFichadaByDocumentoAsync(pDni, pFecha, pHora, pTipMov, pRelojId);
        }
        
        public System.Data.DataSet SetIngresoAndroid(string pLeg, long pDni, string pMov, long pTipMov, decimal pLat, decimal pLon, string pNroTel) {
            return base.Channel.SetIngresoAndroid(pLeg, pDni, pMov, pTipMov, pLat, pLon, pNroTel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SetIngresoAndroidAsync(string pLeg, long pDni, string pMov, long pTipMov, decimal pLat, decimal pLon, string pNroTel) {
            return base.Channel.SetIngresoAndroidAsync(pLeg, pDni, pMov, pTipMov, pLat, pLon, pNroTel);
        }
    }
}
